### ISSUE TITLE
AutoScaling app failed to start saying 'org.ektorp.DbAccessException: Connection refused'

### ISSUE THREAD

**Issue by jessehu** [cloudfoundry-incubator/app-autoscaler#148]
[Note: the original subject and description was removed]

I'm deploying app-autoscaler to my latest Open Source Cloud Foundry. AutoScalingAPI started but AutoScaling and AutoScalingServiceBroker failed to start.

The CF app logs says "org.cloudfoundry.autoscaler.data.couchdb.connection.manager.CouchDbConnectionManager:27 [localhost-startStop-1] [<init>] java.net.ConnectException: Connection refused (Connection refused)". However, I can connect to the CouchDB on 192.168.101.208 using a ruby couchdb client script.  
Verified that the deployed AutoScaling App reads 192.168.101.208 as the CouchDB host (by changed 192.168.101.208 to a192.168.101.208 which throws error '... a192.168.101.208 ...')
All CF VMs are in subnet 192.168.101.0.

Gurus, please give some advise. Thanks in advance.

------- commands and config file --------
mvn clean package -Denv=myenv -DskipTests
bin/deploy.sh myenv

$ cat profiles/myenv.properties 
```
couchdbUsername=autoscaler
couchdbPassword=password
couchdbHost=192.168.101.208
couchdbPort=5984
couchdbServerDBName=couchdb-scaling
couchdbMetricDBPrefix=couchdb-scalingmetric
couchdbBrokerDBName=couchdb-scalingbroker
```

$ cf logs AutoScaling 
```
Connected, tailing logs for app AutoScaling in org xxx / space xxx as xxx ...
2016-12-07T05:58:44.31-0500 [API/0]      OUT Updated app with guid 37aeb982-ca36-4f18-93ac-862abd2480da ({"state"=>"STOPPED"})
2016-12-07T05:58:44.80-0500 [DEA/0]      OUT Got staging request for app with id 37aeb982-ca36-4f18-93ac-862abd2480da
2016-12-07T05:58:46.54-0500 [API/0]      OUT Updated app with guid 37aeb982-ca36-4f18-93ac-862abd2480da ({"state"=>"STARTED"})
2016-12-07T05:58:46.75-0500 [STG/0]      OUT -----> Downloaded app package (5.6M)
2016-12-07T05:58:46.82-0500 [STG/0]      OUT -----> Downloaded app buildpack cache (4.0K)
2016-12-07T05:58:51.08-0500 [STG/0]      OUT -----> Java Buildpack Version: v3.10 (offline) | https://github.com/cloudfoundry/java-buildpack.git#193d6b7
2016-12-07T05:58:56.15-0500 [STG/0]      OUT -----> Downloading Open Jdk JRE 1.8.0_111 from https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_111.tar.gz (found in cache)
2016-12-07T05:58:57.63-0500 [STG/0]      OUT        Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (6.2s)
2016-12-07T05:58:57.63-0500 [STG/0]      OUT -----> Downloading Open JDK Like Memory Calculator 2.0.2_RELEASE from https://java-buildpack.cloudfoundry.org/memory-calculator/trusty/x86_64/memory-calculator-2.0.2_RELEASE.tar.gz (found in cache)
2016-12-07T05:58:57.67-0500 [STG/0]      OUT        Memory Settings: -Xms681574K -XX:MetaspaceSize=104857K -Xss349K -Xmx681574K -XX:MaxMetaspaceSize=104857K
2016-12-07T05:58:57.67-0500 [STG/0]      OUT -----> Downloading Tomcat Instance 8.0.38 from https://java-buildpack.cloudfoundry.org/tomcat/tomcat-8.0.38.tar.gz (found in cache)
2016-12-07T05:58:57.82-0500 [STG/0]      OUT        Expanding Tomcat Instance to .java-buildpack/tomcat (0.1s)
2016-12-07T05:58:57.83-0500 [STG/0]      OUT -----> Downloading Tomcat Lifecycle Support 2.5.0_RELEASE from https://java-buildpack.cloudfoundry.org/tomcat-lifecycle-support/tomcat-lifecycle-support-2.5.0_RELEASE.jar (found in cache)
2016-12-07T05:58:57.83-0500 [STG/0]      OUT -----> Downloading Tomcat Logging Support 2.5.0_RELEASE from https://java-buildpack.cloudfoundry.org/tomcat-logging-support/tomcat-logging-support-2.5.0_RELEASE.jar (found in cache)
2016-12-07T05:58:57.83-0500 [STG/0]      OUT -----> Downloading Tomcat Access Logging Support 2.5.0_RELEASE from https://java-buildpack.cloudfoundry.org/tomcat-access-logging-support/tomcat-access-logging-support-2.5.0_RELEASE.jar (found in cache)
2016-12-07T05:59:00.00-0500 [STG/0]      ERR 
2016-12-07T05:59:11.04-0500 [STG/0]      OUT -----> Uploading droplet (57M)
2016-12-07T05:59:20.35-0500 [DEA/0]      OUT Starting app instance (index 0) with guid 37aeb982-ca36-4f18-93ac-862abd2480da
2016-12-07T05:59:28.16-0500 [App/0]      OUT [CONTAINER] org.apache.coyote.http11.Http11NioProtocol         INFO    Initializing ProtocolHandler ["http-nio-61099"]
2016-12-07T05:59:28.19-0500 [App/0]      OUT [CONTAINER] org.apache.catalina.startup.Catalina               INFO    Initialization processed in 872 ms
2016-12-07T05:59:28.20-0500 [App/0]      OUT [CONTAINER] org.apache.catalina.core.StandardService           INFO    Starting service Catalina
2016-12-07T05:59:28.20-0500 [App/0]      OUT [CONTAINER] org.apache.catalina.core.StandardEngine            INFO    Starting Servlet Engine: Apache Tomcat/8.0.38
2016-12-07T05:59:28.24-0500 [App/0]      OUT [CONTAINER] org.apache.catalina.startup.HostConfig             INFO    Deploying web application directory /home/vcap/app/.java-buildpack/tomcat/webapps/ROOT
2016-12-07T05:59:29.69-0500 [App/0]      OUT [CONTAINER] org.apache.jasper.servlet.TldScanner               INFO    At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2016-12-07T05:59:29.85-0500 [App/0]      OUT 2016-12-07 10:59:29,852 INFO  org.cloudfoundry.autoscaler.core.listener.LifecycleListener:31 [localhost-startStop-1] [<init>] LifecycleListener initialized.
2016-12-07T05:59:31.26-0500 [App/0]      OUT 2016-12-07 10:59:31,260 ERROR org.cloudfoundry.autoscaler.data.couchdb.connection.manager.CouchDbConnectionManager:27 [localhost-startStop-1] [<init>] java.net.ConnectException: Connection refused (Connection refused)
2016-12-07T05:59:31.26-0500 [App/0]      OUT org.ektorp.DbAccessException: java.net.ConnectException: Connection refused (Connection refused)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.ektorp.util.Exceptions.propagate(Exceptions.java:19)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.ektorp.http.StdHttpClient.executeRequest(StdHttpClient.java:183)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.ektorp.http.StdHttpClient.executeRequest(StdHttpClient.java:192)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.ektorp.http.StdHttpClient.head(StdHttpClient.java:146)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.ektorp.http.RestTemplate.head(RestTemplate.java:105)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.ektorp.impl.StdCouchDbInstance.checkIfDbExists(StdCouchDbInstance.java:72)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.ektorp.impl.StdCouchDbInstance.checkIfDbExists(StdCouchDbInstance.java:67)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.cloudfoundry.autoscaler.data.couchdb.connection.manager.CouchDbConnectionManager.initConnection(CouchDbConnectionManager.java:55)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.cloudfoundry.autoscaler.data.couchdb.connection.manager.CouchDbConnectionManager.<init>(CouchDbConnectionManager.java:23)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.cloudfoundry.autoscaler.data.couchdb.connection.manager.ServerDAOManager.<init>(ServerDAOManager.java:40)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.cloudfoundry.autoscaler.data.couchdb.CouchdbStorageService.<init>(CouchdbStorageService.java:99)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.cloudfoundry.autoscaler.data.couchdb.CouchdbStorageService.Initialize(CouchdbStorageService.java:78)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.cloudfoundry.autoscaler.data.couchdb.AutoScalingDataStoreFactory.InitializeAutoScalingDataStore(AutoScalingDataStoreFactory.java:8)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.cloudfoundry.autoscaler.core.listener.LifecycleListener.contextInitialized(LifecycleListener.java:41)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at java.lang.Thread.run(Thread.java:745)
2016-12-07T05:59:31.26-0500 [App/0]      OUT Caused by: java.net.ConnectException: Connection refused (Connection refused)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at java.net.PlainSocketImpl.socketConnect(Native Method)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at java.net.Socket.connect(Socket.java:589)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:178)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.apache.http.impl.client.cache.CachingHttpClient.callBackend(CachingHttpClient.java:747)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.apache.http.impl.client.cache.CachingHttpClient.execute(CachingHttpClient.java:446)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.apache.http.impl.client.cache.CachingHttpClient.execute(CachingHttpClient.java:339)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	at org.ektorp.http.StdHttpClient.executeRequest(StdHttpClient.java:177)
2016-12-07T05:59:31.26-0500 [App/0]      OUT 	... 25 more
2016-12-07T05:59:31.28-0500 [App/0]      OUT 2016-12-07 10:59:31,281 ERROR org.cloudfoundry.autoscaler.core.listener.LifecycleListener:44 [localhost-startStop-1] [contextInitialized] CouchDbConnector may not be null
2016-12-07T05:59:31.28-0500 [App/0]      OUT java.lang.NullPointerException: CouchDbConnector may not be null
2016-12-07T05:59:31.28-0500 [App/0]      OUT 	at org.ektorp.util.Assert.notNull(Assert.java:21)
2016-12-07T05:59:31.28-0500 [App/0]      OUT 	at org.ektorp.support.CouchDbRepositorySupport.<init>(CouchDbRepositorySupport.java:73)

```

**Comment by fraenkel** [comment]
Does the config.properties in your built server/target/server-1.0.war look correct?
Can you get into the container and see if you can access couchdb? Do you have any security groups blocking the outbound connect?

**Comment by jessehu** [comment]
Thanks Michael. config.properties looks good and not modified. I can access the couchdb from the runner vm. There is no security groups settings in my network.

I see that these are iptables rules for the containers on the runner vm and the allowed destination ip range for each containers excludes10.0.0.0/8 and 192.168.0.0/16. my couchdb ip is192.168.101.208. maybe this is the root cause, but i don't know how to modify the defualt allowed networks for new containers.

**Comment by fraenkel** [comment]
You have to fix your default security group rule.

**Comment by jessehu** [comment]
Do you mean this doc https://docs.cloudfoundry.org/adminguide/app-sec-groups.html ? Any specific section? Thanks a lot.

**Comment by fraenkel** [comment]
The default security group only allows communication to public networks. You need to add access to private networks. See the example they have in the provided docs you linked above.

**Comment by jessehu** [comment]
Thanks @fraenkel a lot. My problem is solved after adding a security group for CouchDB server.

```
cf create-security-group my-priviate-sg my-priviate-sg.json
cf bind-security-group my-priviate-sg ORG SPACE 

cat my-priviate-sg.json
[
  {
    "protocol": "tcp",
    "destination": "192.168.101.0-192.168.101.255",
    "ports": "5984",
    "description": "internal CouchDB"
  }
]
```
