### ISSUE TITLE
App not scaling/"Error when polling app"

### ISSUE THREAD

**Issue by georgibarzev** [cloudfoundry-incubator/app-autoscaler#54]
I get the following log entry on the AutoScaling app:

2016-07-21T12:42:21.06-0400 [APP/0]      OUT 2016-07-21 16:42:21,061 ERROR org.cloudfoundry.autoscaler.metric.poller.CFAppStatsPoller:156 [CFAppStatsPoller-Thread-24] [run] Error when polling app a0026054-1cda-416a-9d7c-591dd7ea1424(it might be stopped): null

The app in question is not stopped or missing and has a defined policy, but doesn't scale up or down.

**Comment by fraenkel** [comment]
What did the stack trace associated with this show?
All I can say is that we received an exception with a 404, but we do know the application is started.

**Comment by georgibarzev** [comment]
This is all that is logged, and it seems to get triggered and repeated every 120 seconds like the stepUp/stepDown settings in the policy is configured:
```
2016-07-25T11:37:54.96+0000 [APP/0]      OUT 2016-07-25 11:37:54,967 ERROR org.cloudfoundry.autoscaler.metric.poller.CFAppStatsPoller:156 [CFAppStatsPoller-Thread-3] [run] Error when polling app 22509a8b-eb0e-4b91-a8b9-72b0a1d36525(it might be stopped): null
2016-07-25T11:37:54.96+0000 [APP/0]      OUT java.lang.NullPointerException
2016-07-25T11:37:54.96+0000 [APP/0]      OUT    at org.cloudfoundry.autoscaler.metric.bean.CFInstanceStats$Usage.getTime(CFInstanceStats.java:170)
2016-07-25T11:37:54.96+0000 [APP/0]      OUT    at org.cloudfoundry.autoscaler.metric.poller.CFAppStatsPoller.getAppStats(CFAppStatsPoller.java:237)
2016-07-25T11:37:54.96+0000 [APP/0]      OUT    at org.cloudfoundry.autoscaler.metric.poller.CFAppStatsPoller.run(CFAppStatsPoller.java:126)
2016-07-25T11:37:54.96+0000 [APP/0]      OUT    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2016-07-25T11:37:54.96+0000 [APP/0]      OUT    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
2016-07-25T11:37:54.96+0000 [APP/0]      OUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
2016-07-25T11:37:54.96+0000 [APP/0]      OUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
2016-07-25T11:37:54.96+0000 [APP/0]      OUT    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2016-07-25T11:37:54.96+0000 [APP/0]      OUT    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2016-07-25T11:37:54.96+0000 [APP/0]      OUT    at java.lang.Thread.run(Thread.java:745)
```

This is the current policy for this app:

```
{
  "instanceMinCount": 1,
  "instanceMaxCount": 4,
  "policyTriggers": [
    {
      "metricType": "Memory",
      "statWindow": 300,
      "breachDuration": 600,
      "lowerThreshold": 20,
      "lowerThreshold_set": true,
      "upperThreshold": 50,
      "upperThreshold_set": true,
      "instanceStepCountDown": 1,
      "instanceStepCountUp": 1,
      "stepDownCoolDownSecs": 120,
      "stepUpCoolDownSecs": 120
    }
  ],
  "schedules": null,
  "policyState": "ENABLED"
}
```

**Comment by fraenkel** [comment]
If you pull in the code from PR #32 does this fix your NPE? I have a feeling it is a date/time parse error.

**Comment by georgibarzev** [comment]
Trying the same after fetching the pull/32 code, I actually get 500s on every api call while PUT-ing the policy. Isn't that code at least several commits behind master?

This is autoscalerapi log:
```
2016-07-26T14:29:02.66+0000 [APP/0]      OUT 2016-07-26 14:29:02,666 INFO  org.cloudfoundry.autoscaler.api.rest.PublicRestApi:85 [http-nio-8080-exec-7] [createPolicy] Received JSON String of policy content: {
2016-07-26T14:29:02.66+0000 [APP/0]      OUT     "instanceMinCount":1,
2016-07-26T14:29:02.66+0000 [APP/0]      OUT     "instanceMaxCount":4,
2016-07-26T14:29:02.66+0000 [APP/0]      OUT     "policyTriggers":[{
2016-07-26T14:29:02.66+0000 [APP/0]      OUT         "metricType":"Memory",
2016-07-26T14:29:02.66+0000 [APP/0]      OUT         "statWindow":300,
2016-07-26T14:29:02.66+0000 [APP/0]      OUT         "lowerThreshold":20,
2016-07-26T14:29:02.66+0000 [APP/0]      OUT         "upperThreshold":50,
2016-07-26T14:29:02.66+0000 [APP/0]      OUT         "instanceStepCountDown":1,
2016-07-26T14:29:02.66+0000 [APP/0]      OUT         "instanceStepCountUp":1,
2016-07-26T14:29:02.66+0000 [APP/0]      OUT         "stepDownCoolDownSecs":120,
2016-07-26T14:29:02.66+0000 [APP/0]      OUT         "stepUpCoolDownSecs":120
2016-07-26T14:29:02.66+0000 [APP/0]      OUT     }]
2016-07-26T14:29:02.66+0000 [APP/0]      OUT }
2016-07-26T14:29:02.69+0000 [APP/0]      OUT 2016-07-26 14:29:02,693 INFO  org.cloudfoundry.autoscaler.api.rest.PublicRestApi:111 [http-nio-8080-exec-7] [createPolicy] error in getserverinfo: GET https://api.apps.eu.xxx/info returned a response status of 404 Not Found
2016-07-26T14:29:02.69+0000 [APP/0]      OUT 2016-07-26 14:29:02,694 ERROR org.cloudfoundry.autoscaler.api.util.RestApiResponseHandler:163 [http-nio-8080-exec-7] [getResponseInternalServerError] com.sun.jersey.api.client.UniformInterfaceException: GET https://api.apps.eu.xxx/info returned a response status of 404 Not Found
2016-07-26T14:29:02.69+0000 [RTR/0]      OUT autoscalingapi.apps.eu.xxx - [26/07/2016:14:29:02.540 +0000] "PUT /v1/apps/00cabf96-64d6-4991-8300-4b7dedf0f004/policy/ HTTP/1.1" 500 351 105 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36" 10.0.0.253:39083 x_forwarded_for:"82.36.134.78" x_forwarded_proto:"http" vcap_request_id:52249187-ec79-4764-6aa7-a6ee98275f61 response_time:0.159016983 app_id:02befb0a-d5a8-407a-a9b4-b879d0994008
```
What I find interesting is that the config for the api actually specifies the correct api url:
```
cfUrl=http://api.SYS.eu.xxx/ 
```

and the /info endpoint on it does exist.

**Comment by fraenkel** [comment]
The fix from #32 should only affect how the time from the container metrics is parsed. The above is should a different issue. The url should be /v2/info

**Comment by georgibarzev** [comment]
Applying the code changes from #32 to the current version of master fixed it for me. Thanks.

**Comment by fraenkel** [comment]
After a change occurs, you have a 2 min holding pattern before we start re-evaluating. It is another 2 minutes before we would take action which gives you 4 minutes.
